# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/MaTianlai/开发者/PosteeGen/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):

    def quit_slot(self):
        sys.exit(0)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 750))
        MainWindow.setWindowTitle("PosteeGen")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.newButton = QtWidgets.QPushButton(self.centralwidget)
        self.newButton.setGeometry(QtCore.QRect(100, 360, 241, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.newButton.setFont(font)
        self.newButton.setStyleSheet("font: 18pt \"黑体\";")
        self.newButton.setObjectName("newButton")
        self.descriptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.descriptionLabel.setGeometry(QtCore.QRect(110, 300, 221, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.descriptionLabel.setPalette(palette)
        self.descriptionLabel.setStyleSheet("font: 0 18pt \"Avenir Next\";")
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.titleLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel1.setGeometry(QtCore.QRect(100, 240, 151, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.titleLabel1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(0)
        self.titleLabel1.setFont(font)
        self.titleLabel1.setStyleSheet("font: 0 50pt \"Avenir Next\";")
        self.titleLabel1.setObjectName("titleLabel1")
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setGeometry(QtCore.QRect(100, 480, 241, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.quitButton.setFont(font)
        self.quitButton.setStyleSheet("font: 18pt \"黑体\";")
        self.quitButton.setObjectName("quitButton")
        self.aboutButton = QtWidgets.QPushButton(self.centralwidget)
        self.aboutButton.setGeometry(QtCore.QRect(100, 420, 241, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.aboutButton.setFont(font)
        self.aboutButton.setStyleSheet("font: 18pt \"黑体\";")
        self.aboutButton.setObjectName("aboutButton")
        self.backgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 1000, 750))
        self.backgroundLabel.setMinimumSize(QtCore.QSize(1000, 750))
        self.backgroundLabel.setMaximumSize(QtCore.QSize(1000, 750))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(40)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.backgroundLabel.setFont(font)
        self.backgroundLabel.setStyleSheet("#backgroundLabel {\n"
"    background-color: #24292E;\n"
"}")
        self.backgroundLabel.setText("")
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.titleLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel2.setGeometry(QtCore.QRect(250, 240, 101, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(250, 136, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 136, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.titleLabel2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(50)
        self.titleLabel2.setFont(font)
        self.titleLabel2.setObjectName("titleLabel2")
        self.versionLabel = QtWidgets.QLabel(self.centralwidget)
        self.versionLabel.setGeometry(QtCore.QRect(310, 230, 31, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.versionLabel.setPalette(palette)
        self.versionLabel.setStyleSheet("font: 0 16pt \"Avenir Next\";")
        self.versionLabel.setObjectName("versionLabel")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(440, 140, 441, 441))
        self.imageLabel.setStyleSheet("image: url(:/images/Pgen_Icon.png);")
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.backgroundLabel.raise_()
        self.titleLabel1.raise_()
        self.newButton.raise_()
        self.quitButton.raise_()
        self.descriptionLabel.raise_()
        self.versionLabel.raise_()
        self.titleLabel2.raise_()
        self.aboutButton.raise_()
        self.imageLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.quitButton.clicked.connect(self.quit_slot)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.newButton.setToolTip(_translate("MainWindow", "开始一个生成海报的新流程"))
        self.newButton.setText(_translate("MainWindow", "✙　新海报"))
        self.descriptionLabel.setText(_translate("MainWindow", "绝妙的全自动手抄报合成器"))
        self.titleLabel1.setText(_translate("MainWindow", "Postee"))
        self.quitButton.setToolTip(_translate("MainWindow", "关闭窗口并退出应用"))
        self.quitButton.setText(_translate("MainWindow", "ℚ　退出"))
        self.aboutButton.setToolTip(_translate("MainWindow", "显示该应用的关于信息以及使用条款"))
        self.aboutButton.setText(_translate("MainWindow", "❝　关于"))
        self.titleLabel2.setText(_translate("MainWindow", "Gen"))
        self.versionLabel.setText(_translate("MainWindow", "v1.0"))
        self.imageLabel.setToolTip(_translate("MainWindow", "这个图标好看吗？"))
import Pgen_Icon_rc
