# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TextEditWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 750)
        Dialog.setMinimumSize(QtCore.QSize(1000, 750))
        Dialog.setMaximumSize(QtCore.QSize(1000, 750))
        Dialog.setWindowTitle("新海报 - 文字设置")
        self.continueButton = QtWidgets.QPushButton(Dialog)
        self.continueButton.setGeometry(QtCore.QRect(870, 690, 81, 32))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        self.continueButton.setFont(font)
        self.continueButton.setAutoDefault(True)
        self.continueButton.setDefault(True)
        self.continueButton.setFlat(False)
        self.continueButton.setObjectName("continueButton")
        self.titleInput = QtWidgets.QLineEdit(Dialog)
        self.titleInput.setGeometry(QtCore.QRect(300, 30, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Avenir Next Condensed")
        font.setPointSize(20)
        self.titleInput.setFont(font)
        self.titleInput.setAlignment(QtCore.Qt.AlignCenter)
        self.titleInput.setObjectName("titleInput")
        self.backgroundLabel = QtWidgets.QLabel(Dialog)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 1000, 750))
        self.backgroundLabel.setMinimumSize(QtCore.QSize(1000, 750))
        self.backgroundLabel.setMaximumSize(QtCore.QSize(1000, 750))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(40)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.backgroundLabel.setFont(font)
        self.backgroundLabel.setStyleSheet("#backgroundLabel {\n"
"    background-color: #24292E;\n"
"}")
        self.backgroundLabel.setText("")
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(790, 690, 81, 32))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        self.cancelButton.setFont(font)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setDefault(False)
        self.cancelButton.setFlat(False)
        self.cancelButton.setObjectName("cancelButton")
        self.titleFontBox = QtWidgets.QFontComboBox(Dialog)
        self.titleFontBox.setGeometry(QtCore.QRect(720, 31, 208, 41))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        self.titleFontBox.setFont(font)
        self.titleFontBox.setFontFilters(QtWidgets.QFontComboBox.AllFonts)
        self.titleFontBox.setObjectName("titleFontBox")
        self.textFontBox = QtWidgets.QFontComboBox(Dialog)
        self.textFontBox.setGeometry(QtCore.QRect(40, 680, 208, 41))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        self.textFontBox.setFont(font)
        self.textFontBox.setFontFilters(QtWidgets.QFontComboBox.AllFonts)
        self.textFontBox.setObjectName("textFontBox")
        self.textPointsSpinBox = QtWidgets.QSpinBox(Dialog)
        self.textPointsSpinBox.setGeometry(QtCore.QRect(250, 690, 42, 22))
        self.textPointsSpinBox.setMinimum(10)
        self.textPointsSpinBox.setMaximum(40)
        self.textPointsSpinBox.setProperty("value", 18)
        self.textPointsSpinBox.setObjectName("textPointsSpinBox")
        self.titlePointsSpinBox = QtWidgets.QSpinBox(Dialog)
        self.titlePointsSpinBox.setGeometry(QtCore.QRect(930, 40, 42, 22))
        self.titlePointsSpinBox.setMinimum(10)
        self.titlePointsSpinBox.setMaximum(40)
        self.titlePointsSpinBox.setProperty("value", 18)
        self.titlePointsSpinBox.setObjectName("titlePointsSpinBox")
        self.textEdit_3 = QtWidgets.QPlainTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(40, 390, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(16)
        self.textEdit_3.setFont(font)
        self.textEdit_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QPlainTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(520, 390, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(16)
        self.textEdit_4.setFont(font)
        self.textEdit_4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_2 = QtWidgets.QPlainTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(520, 100, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(16)
        self.textEdit_2.setFont(font)
        self.textEdit_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_1 = QtWidgets.QPlainTextEdit(Dialog)
        self.textEdit_1.setGeometry(QtCore.QRect(40, 100, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(16)
        self.textEdit_1.setFont(font)
        self.textEdit_1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit_1.setPlainText("")
        self.textEdit_1.setObjectName("textEdit_1")
        self.backgroundLabel.raise_()
        self.continueButton.raise_()
        self.titleInput.raise_()
        self.cancelButton.raise_()
        self.titleFontBox.raise_()
        self.textFontBox.raise_()
        self.textPointsSpinBox.raise_()
        self.titlePointsSpinBox.raise_()
        self.textEdit_3.raise_()
        self.textEdit_4.raise_()
        self.textEdit_2.raise_()
        self.textEdit_1.raise_()

        self.retranslateUi(Dialog)
        self.cancelButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.continueButton.setText(_translate("Dialog", "继续"))
        self.titleInput.setToolTip(_translate("Dialog", "在这里输入手抄报的标题。"))
        self.titleInput.setPlaceholderText(_translate("Dialog", "手抄报标题"))
        self.cancelButton.setText(_translate("Dialog", "取消"))
        self.titleFontBox.setToolTip(_translate("Dialog", "手抄报标题的字体。如果你需要的字体没有在下拉菜单中出现，请手动输入字体名称。"))
        self.textFontBox.setToolTip(_translate("Dialog", "手抄报正文的字体。如果你需要的字体没有在下拉菜单中出现，请手动输入字体名称。"))
        self.textPointsSpinBox.setToolTip(_translate("Dialog", "手抄报正文的字体大小，在10～40之间。"))
        self.titlePointsSpinBox.setToolTip(_translate("Dialog", "手抄报标题的字体大小，在10～40之间。"))
        self.textEdit_3.setPlaceholderText(_translate("Dialog", "在这里输入手抄报第3分区的正文。"))
        self.textEdit_4.setPlaceholderText(_translate("Dialog", "在这里输入手抄报第4分区的正文。"))
        self.textEdit_2.setPlaceholderText(_translate("Dialog", "在这里输入手抄报第2分区的正文。"))
        self.textEdit_1.setPlaceholderText(_translate("Dialog", "在这里输入手抄报第1分区的正文。"))
