# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/MaTianlai/开发者/PosteeGen/TextEditWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 750)
        Dialog.setMinimumSize(QtCore.QSize(1000, 750))
        Dialog.setMaximumSize(QtCore.QSize(1000, 750))
        self.continueButton = QtWidgets.QPushButton(Dialog)
        self.continueButton.setGeometry(QtCore.QRect(870, 690, 81, 32))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        self.continueButton.setFont(font)
        self.continueButton.setAutoDefault(True)
        self.continueButton.setDefault(True)
        self.continueButton.setFlat(False)
        self.continueButton.setObjectName("continueButton")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(40, 100, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(300, 30, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(520, 100, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(16)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(40, 390, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(16)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_4.setGeometry(QtCore.QRect(520, 390, 441, 271))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(16)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setObjectName("textEdit_4")
        self.backgroundLabel = QtWidgets.QLabel(Dialog)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 1000, 750))
        self.backgroundLabel.setMinimumSize(QtCore.QSize(1000, 750))
        self.backgroundLabel.setMaximumSize(QtCore.QSize(1000, 750))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(40)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.backgroundLabel.setFont(font)
        self.backgroundLabel.setStyleSheet("#backgroundLabel {\n"
"    background-color: #24292E;\n"
"}")
        self.backgroundLabel.setText("")
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(790, 690, 81, 32))
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        self.cancelButton.setFont(font)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setDefault(False)
        self.cancelButton.setFlat(False)
        self.cancelButton.setObjectName("cancelButton")
        self.backgroundLabel.raise_()
        self.continueButton.raise_()
        self.textEdit.raise_()
        self.lineEdit.raise_()
        self.textEdit_2.raise_()
        self.textEdit_3.raise_()
        self.textEdit_4.raise_()
        self.cancelButton.raise_()

        self.retranslateUi(Dialog)
        self.cancelButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.continueButton.setText(_translate("Dialog", "继续"))
        self.textEdit.setPlaceholderText(_translate("Dialog", "在这里输入手抄报第1分区的正文。"))
        self.lineEdit.setToolTip(_translate("Dialog", "在这里输入手抄报的标题。"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "手抄报标题"))
        self.textEdit_2.setPlaceholderText(_translate("Dialog", "在这里输入手抄报第2分区的正文。"))
        self.textEdit_3.setPlaceholderText(_translate("Dialog", "在这里输入手抄报第3分区的正文。"))
        self.textEdit_4.setPlaceholderText(_translate("Dialog", "在这里输入手抄报第4分区的正文。"))
        self.cancelButton.setText(_translate("Dialog", "取消"))
